package main

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
)

func generateCodeVerifier() (string, error) {
	// The code_verifier is a high-entropy secret generated by the client and kept local.
	// It proves in /callback that the same client that started /login is redeeming the code.
	random := make([]byte, 64) // 64 bytes -> 86 base64url chars (valid PKCE range 43-128)
	if _, err := rand.Read(random); err != nil {
		return "", fmt.Errorf("generate code verifier: %w", err)
	}

	return base64.RawURLEncoding.EncodeToString(random), nil
}

func generateCodeChallenge(verifier string) string {
	// The code_challenge is sent to the authorization server instead of the verifier.
	// Keycloak stores this hash, then later verifies that SHA256(code_verifier) matches.
	sum := sha256.Sum256([]byte(verifier))
	return base64.RawURLEncoding.EncodeToString(sum[:])
}
